# > 美团外卖 - MEITUANWM
^https?:\/\/wmapi\.meituan\.com\/api\/v\d+\/(loadInfo|openscreen|startpicture) url reject
^https?:\/\/p\d\.meituan\.net\/(cell|xianfu) url reject
^https?:\/\/s3plus\.meituan\.net\/v\d\/mss_\w+\/goku\/(lottie|lucency) url reject-img
^https?:\/\/portal-portm\.meituan\.com\/horn_ios url reject

hostname = wmapi.meituan.com, p*.meituan.net, s3plus.meituan.net, portal-portm.meituan.com