# > NOWWA挪瓦咖啡<微信小程序> - NOWWA
^https?:\/\/webapi\.qmai\.cn\/web\/catering\/design\/homePage-Config url script-response-body https://raw.githubusercontent.com/zirawell/Ad-Cleaner/main/Collection/js/wechatApplet.js

hostname = webapi.qmai.cn