# > 堆糖 - DUITANG
^https?:\/\/(www|api)\.duitang\.com\/napi\/ad url reject-dict
^https?:\/\/api\.duitang\.com\/napi\/infra\/settings\/ url reject-dict
^https?:\/\/api\.duitang\.com\/napi\/vienna\/daren\/daren\/recommend\/ url reject-dict

hostname = www.duitang.com, api.duitang.com