# > 高德地图 - AMAP
^https?:\/\/m\d\.amap\.com\/ws\/shield\/dsp\/app\/startup\/init\? url reject-dict
^https?:\/\/m\d\.amap\.com\/ws\/faas\/amap-navigation\/card-service-(car-end|route-plan)\? url reject-dict
^https?:\/\/m\d\.amap\.com\/ws\/shield\/search\/new_hotword\? url reject-dict
^https?:\/\/m\d\.amap\.com\/ws\/valueadded\/ url reject

hostname = m*.amap.com