# > spotify - SPOTIFY
^https?:\/\/spclient\.wg\.spotify\.com\/(ad-logic|ads|.+ad_slot|.+banners|.+canvases|.+cards|.+crashlytics|.+doubleclick.net|.+enabled-tracks|.+event|.+sponsored|.+promoted|.+promoted_offer) url reject-img
^https?:\/\/api\d?\.musical\.ly\/api\/ad\/ url reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v\d\/bootstrap|user-customization-service\/v\d\/customize)$ url script-response-body https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/spotify/proto.js
^https?:\/\/spclient\.wg\.spotify\.com\/(artistview\/v\d\/artist|album-entity-view\/v\d\/album)\/ url script-request-header https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/spotify/json.js

hostname = spclient.wg.spotify.com, api*.musical.ly