# > 滴滴代驾 - DIDIDJ
# ⚠️以下规则可能会影响买单吧代驾权益的使用
;^https?:\/\/daijia\.kuaidadi\.com(:\d+)?\/gateway url reject-dict
^https?:\/\/as\.xiaojukeji\.com\/ep\/as\/conf\?ns=daijia-front&name= url reject-dict

hostname =  daijia.kuaidadi.com, as.xiaojukeji.com