# > eCNY - ECNY
^https?:\/\/mdc\.wallet\.pbcdci\.cn:\d+\/squery url reject-dict
^https?:\/\/mgs\.wallet\.pbcdci\.cn:2201\/mgw\.htm$ url script-response-header https://raw.githubusercontent.com/zirawell/Ad-Cleaner/main/Collection/js/eCNY.js

hostname = mdc.wallet.pbcdci.cn, mgs.wallet.pbcdci.cn