# > 驾校一点通 - JXEDT
^https?:\/\/api\.jxedt\.com\/ad\/ url reject
^https?:\/\/api\.jxedt\.com\/jump\/EMiCcDNp url reject-img
^https?:\/\/gouche\.ksedt\.com\/config\/popup\/ url reject-dict
^https?:\/\/op\.ksedt\.com\/jxedtLive\/liveIntroduceResource url reject-dict
^https?:\/\/richmanrules\.ksedt\.com\/intellectWaterfall(Bidding)?\/find url reject
^https?:\/\/richmanrules\.ksedt\.com\/serverConfig\/\d\/adConfig url reject
^https?:\/\/richmanapi\.jxedt\.com\/api\/(ad|adplus|banadplus)\/ url reject-200
^https?:\/\/richmanmain\.jxedt\.com\/advertisement\/fallback url reject-img

hostname = api.jxedt.com, gouche.ksedt.com, op.ksedt.com, richmanrules.ksedt.com, richmanapi.jxedt.com, richmanmain.jxedt.com