# > 拼多多系通用规则 - PDD_GENERAL
^https?:\/\/video-dsp\.pddpic\.com\/market-dsp-video\/ url reject
^https?:\/\/t-dsp\.pinduoduo\.com\/dspcb\/i\/mrk_union url reject
^https?:\/\/images\.pinduoduo\.com\/(mrk|marketing_api)\/ url reject

hostname = video-dsp.pddpic.com, t-dsp.pinduoduo.com, images.pinduoduo.com